name: Check for new Doom commits

on:
  schedule:
    - cron: "30 5 * * *"

  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: exit $(curl -s https://api.github.com/repos/doomemacs/doomemacs/commits/master | jq -r "((now - (.commit.committer.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
