name: "Build Image"
on:
  workflow_run:
    workflows: ["Check for new Doom commits"]
    types: [completed]

  workflow_dispatch:
    inputs:
      override:
        description: "Manually build image?"
        type: "boolean"
jobs:
  build-image:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.inputs.override }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .github/workflows
          tags: ghcr.io/elken/doom:latest
          push: true
